"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetDetailedTimeRecords = exports.GetTimeRecords = exports.CreateTimeRecord = exports.GetProjects = exports.DeleteProject = exports.GetProject = exports.CreateProject = exports.GetClients = exports.DeleteClient = exports.GetClient = exports.CreateClient = void 0;
exports.CreateClient = "client:create";
exports.GetClient = 'client:get';
exports.DeleteClient = 'client:delete';
exports.GetClients = 'clients:get';
exports.CreateProject = 'project:create';
exports.GetProject = 'project:get';
exports.DeleteProject = 'project:delete';
exports.GetProjects = 'projects:get';
exports.CreateTimeRecord = 'time-record:create';
exports.GetTimeRecords = 'time-records:get';
exports.GetDetailedTimeRecords = 'time-records:detailed:get';
