name: build-app

on:
  push:
    branches: [ main, continuous-integration ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Archive Linux AppImage
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/TimeTracking*.AppImage
      - name: Archive Windows exe
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/TimeTracking*.exe